module.exports = {
  ID_CODE_LENGTH: 8,
  VALIDATE_CODE_LENGTH: 6,
  INVITE_CODE_LENGTH: 8,
  VALIDATE_CODE_EXPIRED_SECONDS: 1200,
  MESSAGE_QUEUE_CHANNEL: 'sendPhoneCode',
  AUTH_JWT_COOKIE_NAME: 'bc_token',
  AUTH_JWT_COOKIE_EXPIRE_SECONDS: 1900,
  AUTH_JWT_EXPIRED_SECONDS: 1800,
  DEFAULT_UNIT: 'BT'
}